kind: Deployment
apiVersion: apps/v1
metadata:
  name: pagination
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pagination
  template:
    metadata:
      labels:
        app: pagination
    spec:
      containers:
        - name: pagination
          image: vaibhavsethia07/pagination:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "100Mi"
              cpu: "300m"
            limits:
              memory: "200Mi"
              cpu: "600m"
      restartPolicy: Always
---
kind: Service
apiVersion: v1
metadata:
  name: pagination
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 31000
  selector:
    app: pagination
